const fishTypes = {
    blue: {
        name: "blue",
        color: "blue",
        speed: 10,
        price: 5,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 8000,
            hunger: 5000,
            healthTimeout: 10000,
            hungerTimeout: 10000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 500,
            reproductionCounter: 1000,
        },
        image: {
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    black: {
        name: "black",
        color: "black",
        speed: 20,
        price: 10,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 10000,
            hunger: 8000,
            healthTimeout: 10000,
            hungerTimeout: 10000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
            reproductionCounter: 1000,
        },
        image: {
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    green: {
        name: "green",
        color: "green",
        speed: 30,
        price: 15,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 1200,
            hunger: 10000,
            healthTimeout: 10000,
            hungerTimeout: 10000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
            reproductionCounter: 1000,
        },
        image: {
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    purple: {
        name: "purple",
        color: "purple",
        speed: 30,
        price: 20,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 1400,
            hunger: 12000,
            healthTimeout: 10000,
            hungerTimeout: 10000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
            reproductionCounter: 1000,
        },
        image: {
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    red: {
        name: "red",
        color: "red",
        speed: 30,
        price: 25,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 16000,
            hunger: 14000,
            healthTimeout: 10000,
            hungerTimeout: 10000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
            reproductionCounter: 1000,
        },
        image: {
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    yellow: {
        name: "yellow",
        color: "yellow",
        speed: 30,
        price: 30,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 1800,
            hunger: 16000,
            healthTimeout: 10000,
            hungerTimeout: 10000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
            reproductionCounter: 1000,
        },
        image: {
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
};

const menuData = {
    select: {
        name: "SELECT",
        width: 200,
        height: 200,
    },
    food: {
        name: "FOOD",
        width: 100,
        height: 173,
    },
    pill: {
        name: "PILL",
        width: 124,
        height: 256,
    },
    clean: {
        name: "CLEAN",
        width: 90,
        height: 78,
    },
    fishShop: {
        name: "BUY FISH",
        width: 128,
        height: 128,
    },
    shop: {
        name: "SHOP",
        width: 128,
        height: 128,
    },
};

const decorationData = {
    background0: {
        price: 0,
    },
    background1: {
        price: 10,
    },
    background2: {
        price: 20,
    },
    background3: {
        price: 30,
    },
    background4: {
        price: 40,
    },
};
export { fishTypes, menuData, decorationData };
