const fishTypes = {
    blue: {
        name: "blue",
        color: "blue",
        speed: 10,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 2500,
            hunger: 2000,
            healthTimeout: 5000,
            hungerTimeout: 5000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 500,
        },
        image: {
            leftSrc: "blue_left.png",
            rightSrc: "blue_right.png",
            spriteWidth: 1992,
            spriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    black: {
        name: "black",
        color: "black",
        speed: 20,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 3500,
            hunger: 3000,
            healthTimeout: 5000,
            hungerTimeout: 5000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
        },
        image: {
            leftSrc: "black_left.png",
            rightSrc: "black_right.png",
            totalSpriteWidth: 1992,
            totalSpriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
    green: {
        name: "green",
        color: "green",
        speed: 30,
        maxHealthMeter: 100,
        maxhungerMeter: 100,
        baseSize: 9,
        changeInterval: {
            health: 4500,
            hunger: 5000,
            healthTimeout: 5000,
            hungerTimeout: 5000,
            changeXDirection: 5000,
            changeYDirection: 4000,
            resetYDirection: 500,
            levelUp: 2000,
        },
        image: {
            leftSrc: "green_left.png",
            rightSrc: "green_right.png",
            spriteWidth: 1992,
            spriteHeight: 981,
            spriteX: 4,
            spriteY: 3,
        },
    },
};

export { fishTypes };
